book_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book_logs.urls', namespace='book_logs') ),
]

book_logs/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from rest_framework.urlpatterns import format_suffix_patterns


app_name = 'book_logs'
urlpatterns = [
    # Homepage
    url(r'^$', views.index, name='index'),
    # Detail page for a single book
    url(r'^/(?P<book_id>\d+)/$', views.book, name='book'),
    # Rest framework path
    path('booklist/', views.BookList.as_view()),
    path('booklist/<int:pk>/', views.BookDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

book_logs/models.py
from django.db import models

# Create informations of books in Book model


class Book(models.Model):
    title = models.CharField(max_length=60)
    author = models.CharField(max_length=140, blank=True)
    rating = models.CharField(max_length=60, blank=True)
    voters = models.CharField(max_length=60, blank=True)
    price = models.CharField(max_length=60, blank=True)
    currency = models.CharField(max_length=60, blank=True)
    description = models.TextField()
    publisher = models.CharField(max_length=60, blank=True)
    page_count = models.CharField(max_length=60, blank=True)
    generes = models.CharField(max_length=60, blank=True)
    ISBN = models.CharField(max_length=60)
    language = models.CharField(max_length=60, blank=True)
    published_date = models.CharField(max_length=60, blank=True)

    def __str__(self):
        return self.title

book_logs/views.py
import csv
from django.shortcuts import render
from .models import Book
from .serializers import BookSerializer
from rest_framework import generics
from django.http import HttpResponse
from django.db.models import Q
import pickle


# BookList and BookDetail class used a restful framwork for CRUD
class BookList(generics.ListCreateAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer


class BookDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer


# View function index for homepage and showed titel of books
# Make a search with query
# Make a list of searches in list.pkl file

searches = []


def index(request):
    global searches

    query = request.GET.get('q', None)
    books = Book.objects.order_by('pk')
    if query is not None:
        books = Book.objects.filter(
            Q(title__icontains=query)
        )
    context = {'books': books}
    searches.append(query)
    with open('list.pkl', 'wb') as f:
        pickle.dump(searches, f)

    return render(request, 'book_logs/index.html', context)

# View function book for detail of each books


def book(request, book_id):
    book = Book.objects.get(id=book_id)
    author = book.author
    rating = book.rating
    voters = book.voters
    price = book.price
    currency = book.currency
    description = book.description
    publisher = book.publisher
    page_count = book.page_count
    generes = book.generes
    ISBN = book.ISBN
    language = book.language
    published_date = book.published_date

    context = {'book': book, 'author': author,
               'rating': rating, 'voters': voters, 'price': price,
               'currency': currency, 'description': description,
               'publisher': publisher, 'page_count': page_count, 'generes': generes,
               'ISBN': ISBN, 'language': language,
               'published_date': published_date}
    return render(request, 'book_logs/book.html', context)

book_logs/templates/book_logs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- CSS -->
    <link rel="stylesheet" href="index.css">
    <title>
        Book LOg
    </title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>

    <nav class="navbar navbar-default navbar-static-top">
        <a class="navbar-brand" href="{% url 'book_logs:index' %}">
            Book Log
        </a>
    </nav>


    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div> <!-- /container -->


</body>

</html>

book_logs/templates/book_logs/book.html
{% extends 'book_logs/base.html' %}

{% block content %}

<p>Book: {{book}}</p>
<p>Author: {{author}}</p>
<p>Rating: {{rating}}</p>
<p>Voters: {{voters}}</p>
<p>Price: {{price}}</p>
<p>Currency: {{currency}}</p>
<p>Description:{{description}}</p>
<p>Publisher:{{publisher}}</p>
<p>Pages:{{page_count}}</p>
<p>Generes:{{generes}}</p>
<p>ISBN:{{ISBN}}</p>
<p>Language:{{language}}</p>
<p>Published Date:{{published_date}}</p>

{% endblock content %}

book_logs/templates/book_logs/index.html
{% extends "book_logs/base.html" %}
{% block header %}
<div class='jumbotron'>
    <h1>Book</h1>
</div>
{% endblock header %}
{% block content %}
<div class="jumbotron border shadow">
    <div class="row">
        <div class="col-md-8 offset-2">
            <form>
                <div class="input-group">
                    <input name="q" type="text" placeholder="Search" class="form-control form-control-lg" />
                    <div class="input-group-append">
                        <button class="btn btn-dark btn-lg">Search</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="panel panel-default">


        {% for book in books %}
        <div class="panel-heading">
            <h3>
                <a href="{% url 'book_logs:book' book.id %}">{{book}}</a>
            </h3>
        </div>
        {% empty %}
        <p>No book have been added yet.</p>
        {% endfor %}

        {% endblock content %}